package api

var GameWords = []string{
	"apple", "banana", "cherry", "grape", "orange", "strawberry", "blueberry", "watermelon",
	"mango", "pineapple", "peach", "pear", "plum", "kiwi", "lemon", "lime", "coconut", "papaya",
	"avocado", "fig", "date", "apricot", "tangerine", "nectarine", "grapefruit", "pomegranate",
	"cheese", "butter", "milk", "yogurt", "cream", "ice cream", "chocolate", "candy", "cookie",
	"cake", "bread", "toast", "cereal", "pasta", "rice", "beans", "corn", "carrot", "broccoli",
	"spinach", "lettuce", "cucumber", "tomato", "potato", "onion", "garlic", "pepper", "salt", "sugar",
	"honey", "jam", "peanut butter", "olive oil", "vinegar", "soy sauce", "ketchup", "mustard", "mayonnaise", "ranch",
	"pizza", "burger", "hotdog", "sandwich", "taco", "burrito", "noodles", "soup", "stew", "curry",
	"salad", "sushi", "steak", "chicken", "fish", "shrimp", "bacon", "ham", "turkey", "sausage",
	"egg", "waffle", "pancake", "donut", "muffin", "bagel", "pretzel", "popcorn", "chips", "nuts",
	"coffee", "tea", "juice", "soda", "water", "beer", "wine", "whiskey", "vodka", "rum",
	"gin", "tequila", "brandy", "champagne", "martini", "cocktail", "margarita", "mojito", "daiquiri", "sangria",
	"cat", "dog", "bird", "fish", "hamster", "rabbit", "guinea pig", "ferret", "mouse", "rat",
	"squirrel", "deer", "rabbit", "fox", "wolf", "bear", "lion", "tiger", "elephant", "giraffe",
	"zebra", "rhinoceros", "hippopotamus", "cheetah", "leopard", "jaguar", "puma", "cougar", "lynx", "panther",
	"monkey", "ape", "gorilla", "chimpanzee", "orangutan", "baboon", "lemur", "koala", "panda", "penguin",
	"ostrich", "peacock", "swan", "duck", "goose", "chicken", "turkey", "eagle", "hawk", "owl",
	"parrot", "flamingo", "crane", "heron", "stork", "albatross", "pelican", "seagull", "raven", "crow",
	"snake", "lizard", "turtle", "crocodile", "alligator", "frog", "toad", "salamander", "newt", "gecko",
	"octopus", "squid", "jellyfish", "starfish", "clam", "oyster", "crab", "lobster", "shrimp", "seahorse",
	"whale", "dolphin", "shark", "tuna", "salmon", "trout", "catfish", "cod", "halibut", "bass",
	"butterfly", "bee", "ant", "spider", "beetle", "dragonfly", "mosquito", "fly", "wasp", "hornet",
	"grasshopper", "cricket", "cockroach", "termite", "ladybug", "firefly", "worm", "snail", "slug", "leech",
	"tree",
	"bamboo", "cactus", "rose", "tulip", "daisy", "sunflower",
	"lavender", "lilac", "crocus",
	"daffodil", "hyacinth", "geranium", "marigold", "zinnia", "chrysanthemum", "petunia", "pansy", "violet", "primrose",
	"mountain", "hill", "valley", "canyon", "river", "lake", "ocean", "sea", "beach", "island",
	"volcano", "glacier", "desert", "forest", "jungle", "savanna", "tundra", "meadow", "prairie", "plain",
	"swamp", "marsh", "wetland", "bay", "gulf", "strait", "lagoon", "fjord", "delta", "estuary",
	"cliff", "cave", "waterfall", "spring", "stream", "creek", "brook", "pond", "reservoir", "harbor",
	"town", "city", "village", "metropolis", "suburb", "castle", "mansion", "cottage", "cabin", "hut",
	"tent", "igloo", "tipi", "pagoda", "temple", "church", "synagogue", "mosque", "monastery", "convent",
	"palace", "fortress", "tower", "bridge", "tunnel", "aqueduct", "wall", "gate", "arch", "dome",
	"pyramid", "monument", "statue", "fountain", "plaza", "park", "garden", "vineyard", "orchard", "farm",
	"ranch", "stable", "barn", "silo", "mill", "factory", "warehouse", "market", "shop", "store",
	"office", "school", "hospital", "library", "museum", "theater", "cinema", "stadium", "arena", "gymnasium",
	"swimming pool", "skating rink", "bowling alley", "golf course", "tennis court", "basketball court", "baseball field", "soccer field", "football field", "hockey rink",
	"car", "truck", "bus", "taxi", "train", "subway", "tram", "bicycle", "motorcycle", "scooter",
	"skateboard", "roller skates", "airplane", "helicopter", "hot air balloon", "boat", "ship", "submarine", "sailboat", "canoe",
	"kayak", "raft", "barge", "yacht", "cruise ship", "ferry", "tanker", "fishing boat", "tugboat", "speedboat",
	"rocket", "satellite", "space shuttle", "rover", "drone", "glider", "blimp", "zeppelin", "hang glider", "parachute",
	"umbrella", "hat", "cap", "beanie", "scarf", "gloves", "mittens", "socks", "shoes", "boots",
	"sandals", "slippers", "sneakers", "heels", "flats", "loafers", "oxfords", "pumps", "stilettos", "wedges",
	"shirt", "t-shirt", "tank top", "sweater", "hoodie", "jacket", "coat", "blazer", "cardigan", "vest",
	"pants", "jeans", "shorts", "skirt", "dress", "gown", "robe", "kimono", "tunic", "toga",
	"leotard", "tights", "stockings", "belt", "tie", "bowtie", "suspenders", "buckle", "button", "zipper",
	"pocket", "sleeve", "collar", "cuff", "hem", "seam", "label", "tag", "lace", "ribbon",
	"flower", "vine", "herb", "grass", "moss", "mushroom", "toadstool",
	"camera", "phone", "laptop", "computer", "tablet", "watch", "calculator", "clock", "radio", "television",
	"microphone", "speaker", "headphones", "earbuds", "keyboard", "mouse", "monitor", "printer", "scanner", "copier",
	"camera lens", "telescope", "microscope", "binoculars", "magnifying glass", "mirror", "flashlight", "lantern", "candle", "torch",
	"lightbulb", "lamp", "chandelier", "fan", "heater", "air conditioner", "refrigerator", "oven", "stove", "microwave",
	"dishwasher", "washing machine", "dryer", "vacuum", "blender", "toaster", "coffee maker", "kettle", "iron", "sewing machine",
	"book", "magazine", "newspaper", "comic", "novel", "poem", "letter", "postcard", "envelope", "stamp",
	"pencil", "pen", "marker", "crayon", "pencil sharpener", "eraser", "ruler", "compass", "protractor", "calculator",
	"notebook", "journal", "diary", "planner", "calendar", "map", "chart", "graph", "diagram", "blueprint",
	"painting", "sculpture", "drawing", "sketch", "photograph", "print", "poster", "sign", "billboard", "mural",
	"mosaic", "tile", "wallpaper", "carpet", "rug", "blanket", "pillow", "mattress", "bed", "couch",
	"chair", "table", "desk", "dresser", "cabinet", "shelf", "bookcase", "wardrobe", "closet", "drawer",
	"door", "window", "curtain", "blind", "shade", "screen", "shutter", "awning", "porch", "deck",
	"patio", "balcony", "terrace", "staircase", "ladder", "ramp", "hallway", "room", "basement", "attic",
	"kitchen", "bedroom", "bathroom", "living room", "dining room", "office", "garage", "laundry room", "pantry", "cellar",
	"sink", "toilet", "bathtub", "shower", "shower curtain", "towel", "soap", "shampoo", "toothbrush", "toothpaste",
	"hairbrush", "comb", "mirror", "scale", "thermometer", "blood pressure cuff", "stethoscope", "syringe", "bandage", "gauze",
	"pill", "capsule", "tablet", "syrup", "injection", "ointment", "cream", "lotion", "powder", "spray",
	"perfume", "cologne", "deodorant", "antiperspirant", "sunscreen", "lip balm", "makeup", "mascara", "lipstick", "eyeshadow",
	"nail polish", "nail file", "nail clippers", "tweezers", "razor", "shaving cream", "aftershave", "hair gel", "hair spray", "hair dye",
	"ring", "necklace", "bracelet", "earring", "pendant", "locket", "brooch", "pin", "buckle", "button",
	"gemstone", "diamond", "pearl", "ruby", "sapphire", "emerald", "amethyst", "topaz", "opal", "jade",
	"gold", "silver", "bronze", "copper", "iron", "steel", "aluminum", "titanium", "platinum", "mercury",
	"glass", "plastic", "rubber", "leather", "wool", "cotton", "silk", "linen", "polyester", "nylon",
	"canvas", "denim", "velvet", "satin", "lace", "fleece",
	"music", "song", "melody", "harmony", "rhythm", "beat", "tempo", "note", "chord", "scale",
	"piano", "guitar", "violin", "cello", "bass", "drum", "trumpet", "saxophone", "flute", "clarinet",
	"trombone", "tuba", "harmonica", "accordion", "mandolin", "banjo", "ukulele", "harp", "organ", "synthesizer",
	"microphone", "amplifier", "speaker", "headphones", "earbuds", "stereo", "radio", "turntable", "cd player", "mp3 player",
	"sports", "basketball", "baseball", "football", "soccer", "hockey", "tennis", "golf", "bowling", "badminton",
	"volleyball", "table tennis", "badminton", "baseball", "softball", "hockey", "rugby",
	"swimming", "diving", "surfing", "kayaking", "canoeing", "rowing", "sailing", "fishing", "ice skating", "roller skating",
	"skateboarding", "snowboarding", "skiing", "sledding", "curling", "archery", "shooting", "fencing", "wrestling", "boxing",
	"martial arts", "judo", "karate", "taekwondo", "gymnastics", "cheerleading", "dance", "ballet", "tap dancing", "hip hop",
	"salsa", "tango", "waltz", "swing", "ballet", "tap dancing",
	"yoga", "pilates", "tai chi", "meditation", "running", "jogging", "hiking", "rock climbing", "mountain biking", "horseback riding",
	"painting", "drawing", "sculpture", "pottery", "jewelry making", "woodworking", "metalworking", "glass blowing", "weaving", "knitting",
	"crocheting", "embroidery", "quilting", "sewing", "macrame", "origami", "paper cutting", "calligraphy", "photography", "videography",
	"cooking", "baking", "grilling", "smoking", "roasting", "boiling", "frying", "sauteing", "steaming", "braising",
	"gardening", "landscaping", "composting", "beekeeping", "herb growing", "vegetable gardening", "flower gardening", "bonsai", "terrarium", "aquarium",
	"reading", "writing", "journaling", "blogging", "storytelling", "poetry", "fiction", "non-fiction", "biography", "memoir",
	"history", "science", "math", "physics", "chemistry", "biology", "geography",
	"game", "puzzle", "riddle", "crossword", "sudoku", "chess", "checkers", "board game", "card game", "video game",
	"console", "controller", "joystick", "arcade", "pinball", "dice", "domino", "tile", "marble", "toy",
	"doll", "action figure", "stuffed animal", "lego", "puzzle piece", "building block", "balloon", "kite", "frisbee", "ball",
	"baseball", "basketball", "football", "soccer ball", "tennis ball", "golf ball", "bowling ball", "billiard ball", "ping pong ball", "beach ball",
	"rocket", "airplane model", "train set", "car model", "boat model", "helicopter model", "drone", "robot", "remote control car", "radio controlled plane",
	"sun", "moon", "star", "planet", "comet", "meteor", "asteroid", "black hole", "nebula", "galaxy",
	"cloud", "rain", "snow", "sleet", "hail", "fog", "mist", "storm", "hurricane", "tornado",
	"lightning", "thunder", "wind", "breeze", "gust", "hurricane force wind", "calm", "gentle", "strong", "powerful",
	"earthquake", "tsunami", "avalanche", "landslide", "mudslide", "flood", "drought", "wildfire", "blizzard", "heat wave",
	"season", "spring", "summer", "autumn", "winter", "year", "month", "week", "day", "hour",
	"minute", "second", "morning", "afternoon", "evening", "night", "midnight", "noon", "sunrise", "sunset",
	"dawn", "dusk", "twilight", "daylight", "darkness", "light", "shadow", "reflection", "echo", "silence",
	"sound", "noise", "music", "voice", "laugh", "cry", "scream", "whisper", "shout", "roar",
	"color", "red", "blue", "green", "yellow", "orange", "purple", "pink", "brown", "black",
	"white", "gray", "silver", "gold", "bronze", "copper", "rainbow", "sunset", "sunrise", "twilight",
	"shape", "circle", "square", "rectangle", "triangle", "pentagon", "hexagon", "heptagon", "octagon", "diamond",
	"star", "heart", "crescent", "spiral", "wave", "line", "curve", "angle", "point", "edge",
	"size", "small", "medium", "large", "tiny", "huge", "tall", "short", "wide", "narrow", "thick", "thin",
	"texture", "smooth", "rough", "soft", "hard", "fuzzy", "slippery", "sticky", "bumpy", "scratchy",
	"temperature", "hot", "cold", "warm", "cool", "frozen", "boiling", "lukewarm", "chilly", "scorching",
	"taste", "sweet", "sour", "salty", "bitter", "spicy", "savory", "bland", "tangy", "mild",
	"smell", "fragrant", "stinky", "fresh", "floral", "fruity", "earthy",
	"number",
	"country", "usa", "canada", "mexico", "france", "germany", "italy", "spain", "england", "scotland",
	"ireland", "wales", "japan", "china", "india", "australia", "brazil", "argentina", "egypt", "russia",
	"africa", "europe", "asia", "south america", "north america", "antarctica", "oceania", "middle east", "arctic", "caribbean",
	"state", "province", "city", "county", "region", "district",
	"capital", "border", "coast", "inland", "beach", "river", "mountain", "valley", "hill",
	"holiday", "christmas", "thanksgiving", "easter", "halloween", "valentine's day", "mother's day", "father's day", "independence day", "new year",
	"birthday", "anniversary", "wedding", "funeral", "graduation", "retirement", "promotion", "celebration", "party", "festival",
	"carnival", "parade", "fireworks", "decoration", "costume", "mask", "present", "gift", "cake", "candle",
	"profession", "doctor", "nurse", "teacher", "engineer", "architect", "lawyer", "judge", "chef", "baker",
	"butcher", "farmer", "gardener", "carpenter", "plumber", "electrician", "mechanic", "welder", "painter", "sculptor",
	"actor", "actress", "singer", "dancer", "musician", "composer", "director", "producer", "screenwriter", "author",
	"journalist", "photographer", "artist", "designer", "animator", "programmer", "developer", "hacker", "scientist", "researcher",
	"professor", "student", "athlete", "coach", "referee", "umpire", "trainer", "therapist", "counselor", "psychologist",
	"police officer", "firefighter", "paramedic", "security guard", "soldier", "sailor", "pilot", "astronaut", "explorer", "archaeologist",
	"emotion", "happy", "sad", "angry", "scared", "excited", "bored", "confused", "surprised", "disappointed",
	"grateful", "proud", "ashamed", "jealous", "envious", "anxious", "calm", "relaxed", "stressed", "tired",
	"energetic", "lazy", "motivated", "discouraged", "hopeful", "hopeless", "confident", "insecure", "brave", "cowardly",
	"body part", "head", "face", "eye", "ear", "nose", "mouth", "tooth", "tongue", "lip",
	"chin", "cheek", "forehead", "hair", "neck", "shoulder", "arm", "elbow", "wrist", "hand",
	"finger", "thumb", "palm", "fist", "nail", "knuckle", "chest", "breast", "back", "waist",
	"hip", "leg", "thigh", "knee", "shin", "ankle", "foot", "toe", "heel", "sole",
	"organ", "brain", "heart", "lung", "liver", "kidney", "pancreas", "stomach", "intestine", "muscle",
}
